/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MinesweeperGUI */

#ifndef _Included_MinesweeperGUI
#define _Included_MinesweeperGUI
#ifdef __cplusplus
extern "C" {
#endif
#undef MinesweeperGUI_FOCUS_TRAVERSABLE_UNKNOWN
#define MinesweeperGUI_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef MinesweeperGUI_FOCUS_TRAVERSABLE_DEFAULT
#define MinesweeperGUI_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef MinesweeperGUI_FOCUS_TRAVERSABLE_SET
#define MinesweeperGUI_FOCUS_TRAVERSABLE_SET 2L
#undef MinesweeperGUI_TOP_ALIGNMENT
#define MinesweeperGUI_TOP_ALIGNMENT 0.0f
#undef MinesweeperGUI_CENTER_ALIGNMENT
#define MinesweeperGUI_CENTER_ALIGNMENT 0.5f
#undef MinesweeperGUI_BOTTOM_ALIGNMENT
#define MinesweeperGUI_BOTTOM_ALIGNMENT 1.0f
#undef MinesweeperGUI_LEFT_ALIGNMENT
#define MinesweeperGUI_LEFT_ALIGNMENT 0.0f
#undef MinesweeperGUI_RIGHT_ALIGNMENT
#define MinesweeperGUI_RIGHT_ALIGNMENT 1.0f
#undef MinesweeperGUI_serialVersionUID
#define MinesweeperGUI_serialVersionUID -7644114512714619750i64
#undef MinesweeperGUI_serialVersionUID
#define MinesweeperGUI_serialVersionUID 4613797578919906343i64
#undef MinesweeperGUI_INCLUDE_SELF
#define MinesweeperGUI_INCLUDE_SELF 1L
#undef MinesweeperGUI_SEARCH_HEAVYWEIGHTS
#define MinesweeperGUI_SEARCH_HEAVYWEIGHTS 1L
#undef MinesweeperGUI_OPENED
#define MinesweeperGUI_OPENED 1L
#undef MinesweeperGUI_serialVersionUID
#define MinesweeperGUI_serialVersionUID 4497834738069338734i64
#undef MinesweeperGUI_DEFAULT_CURSOR
#define MinesweeperGUI_DEFAULT_CURSOR 0L
#undef MinesweeperGUI_CROSSHAIR_CURSOR
#define MinesweeperGUI_CROSSHAIR_CURSOR 1L
#undef MinesweeperGUI_TEXT_CURSOR
#define MinesweeperGUI_TEXT_CURSOR 2L
#undef MinesweeperGUI_WAIT_CURSOR
#define MinesweeperGUI_WAIT_CURSOR 3L
#undef MinesweeperGUI_SW_RESIZE_CURSOR
#define MinesweeperGUI_SW_RESIZE_CURSOR 4L
#undef MinesweeperGUI_SE_RESIZE_CURSOR
#define MinesweeperGUI_SE_RESIZE_CURSOR 5L
#undef MinesweeperGUI_NW_RESIZE_CURSOR
#define MinesweeperGUI_NW_RESIZE_CURSOR 6L
#undef MinesweeperGUI_NE_RESIZE_CURSOR
#define MinesweeperGUI_NE_RESIZE_CURSOR 7L
#undef MinesweeperGUI_N_RESIZE_CURSOR
#define MinesweeperGUI_N_RESIZE_CURSOR 8L
#undef MinesweeperGUI_S_RESIZE_CURSOR
#define MinesweeperGUI_S_RESIZE_CURSOR 9L
#undef MinesweeperGUI_W_RESIZE_CURSOR
#define MinesweeperGUI_W_RESIZE_CURSOR 10L
#undef MinesweeperGUI_E_RESIZE_CURSOR
#define MinesweeperGUI_E_RESIZE_CURSOR 11L
#undef MinesweeperGUI_HAND_CURSOR
#define MinesweeperGUI_HAND_CURSOR 12L
#undef MinesweeperGUI_MOVE_CURSOR
#define MinesweeperGUI_MOVE_CURSOR 13L
#undef MinesweeperGUI_NORMAL
#define MinesweeperGUI_NORMAL 0L
#undef MinesweeperGUI_ICONIFIED
#define MinesweeperGUI_ICONIFIED 1L
#undef MinesweeperGUI_MAXIMIZED_HORIZ
#define MinesweeperGUI_MAXIMIZED_HORIZ 2L
#undef MinesweeperGUI_MAXIMIZED_VERT
#define MinesweeperGUI_MAXIMIZED_VERT 4L
#undef MinesweeperGUI_MAXIMIZED_BOTH
#define MinesweeperGUI_MAXIMIZED_BOTH 6L
#undef MinesweeperGUI_serialVersionUID
#define MinesweeperGUI_serialVersionUID 2673458971256075116i64
/*
 * Class:     MinesweeperGUI
 * Method:    requestMapFromCpp
 * Signature: (IJZ)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_MinesweeperGUI_requestMapFromCpp
  (JNIEnv *, jobject, jint, jlong, jboolean);

/*
 * Class:     MinesweeperGUI
 * Method:    getFloodFill
 * Signature: (IIJ)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_MinesweeperGUI_getFloodFill
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     MinesweeperGUI
 * Method:    setupcpp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_MinesweeperGUI_setupcpp
  (JNIEnv *, jobject);

/*
 * Class:     MinesweeperGUI
 * Method:    endofgamecpp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_MinesweeperGUI_endofgamecpp
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
